#cloud-config
package_update: true
packages:
  - build-essential
  - cargo
  - sudo
write_files:
  - path: "/etc/environment"
    append: true
    content: |
      CARGO_TARGET_DIR="/home/ubuntu/target"
runcmd:
  - rustup component add rustfmt
